Add logger
ThorpeJosh/tp-timesheet pull request #24
Opened 2022-10-06 09:31 UTC by lamchuntat

@ThorpeJosh @siewyeng @changukshin 
Need some advice for this PR. The logger that I added to `__main__.py` cannot be used in other modules, ie. only log messages from `__main__.py` are recorded, log messages from other modules couldn't be seen in stdout nor the log file :/

2022-10-06 09:32 UTC, lamchuntat commented
Perhaps this link could be useful: https://docs.python.org/3/howto/logging.html#logging-from-multiple-modules

2022-10-06 09:45 UTC, ThorpeJosh commented on tp_timesheet/submit_form.py
> +logger.info("HELLOOOOOOO")
Same here

2022-10-06 09:51 UTC, ThorpeJosh commented
Lastly just from the docs, I believe they all should be referencing the same logger if you don't want seperate log files or behaviour for different modules. So the `getLogger()` call should have same name as the logger in `__main__.py` where you are attaching the handlers.

2022-10-07 05:58 UTC, lamchuntat commented
Shifted setup for logger into the `__init__.py` file. Loggers in other modules are now working with the same configuration. I've also replaced all existing print statements with logs.

@ThorpeJosh @siewyeng @changukshin please advise me on whether there will be any potential issues with setting up the logger in this way and if the logging levels are appropriate for the print statements they are replacing. Any other suggestions are greatly welcomed.

2022-10-07 08:12 UTC, ThorpeJosh requested changes

2022-10-07 08:12 UTC, ThorpeJosh commented on tp_timesheet/__init__.py
> +log_dir = Path.home().joinpath(".config", "tp-timesheet.log")
log should maybe go inside the `.config/tp-timesheet/logs/` directory so it doesn't fill up the users `.config`

2022-10-07 08:14 UTC, ThorpeJosh commented on tp_timesheet/__init__.py
> +file_handler = logging.FileHandler(log_dir)
You ok to try the rotation logs instead of one log file?

Maybe rotate logs every month?

2022-10-07 08:26 UTC, lamchuntat commented on tp_timesheet/__init__.py
> +file_handler = logging.FileHandler(log_dir)
Yup let's do that, every month sounds good

2022-10-12 05:53 UTC, lamchuntat commented
@ThorpeJosh @siewyeng @changukshin 

Finally managed to get the checks to pass 😮‍💨 Could you help me review and merge if all's good?

2022-10-12 07:04 UTC, ThorpeJosh requested changes
Looks good.

Previously we controlled the "debug" print statements with:
```python
if args.verbose:
     print('log message')
```
But now we want to replace them all with simply `logger.debug('log message')` and instead set the `stream_handler` level to INFO or DEBUG according to the args.verbose. This way the debug messages will always go to the log file but not necessarily to stdout.

2022-10-13 06:09 UTC, merged