adding unit tests / updating date parsing logic
ThorpeJosh/tp-timesheet pull request #26
Opened 2022-10-08 10:17 UTC by changukshin

There was a bug of parsing 4 digit year. Fixed.

Bug:
 - '8/10/2022' goes to 'MDY'.

Unit Tests all passed.

2022-10-08 10:20 UTC, changukshin commented
Code reformatting needed.
Will be done by monday.

2022-10-10 06:13 UTC, changukshin commented
All passed and looks good to go.
Review required.

2022-10-10 07:16 UTC, ThorpeJosh requested changes
Nice!

2022-10-10 07:16 UTC, ThorpeJosh commented on tp_timesheet/tests/test_submit_various_date_formats.py
> +    today = datetime.datetime.today()
I think we should also test a few other dates (ambiguous and challenging ones) so that the test is reproducible.
Possibly even a range of dates (since we have the compute power)

2022-10-10 07:16 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> -            start_date = dateutil.parser.parse(start_date_arg)
Nice catch. Exactly what unit tests are for.

Can you please move this get_start_date function into the dates.py module? I think it is a more appropriate location

2022-10-10 07:16 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> -            start_date = dateutil.parser.parse(start_date_arg)
And also rename it to 'date_utils.py', 'tp_date_tools.py' or something as 'dates' makes me nervous due to being a similar name to the inbuilt datetime and date libraries (can cause namespace/import conflicts).

2022-10-10 09:01 UTC, changukshin commented
All resolved.
Need review.

@ThorpeJosh  @siewyeng @lamchuntat

2022-10-10 10:02 UTC, ThorpeJosh commented
Can you please add the `pytest` command to the readme so other know how to run the new check?
Thanks

2022-10-11 02:54 UTC, changukshin commented on tp_timesheet/tests/test_submit_various_date_formats.py
> +from tp_timesheet.__main__ import get_start_date
I think os/sys/datetime.* still needed. (correct me if I am wrong)
tp_timesheet.__main__ is updated to tp_timesheet.date_utils on e3a1100

2022-10-11 03:01 UTC, changukshin commented
Jenkins CI branch failed.
It seems like just a temporary failed.
Could you address this?
and could you letting me know how could I manually re-run branch check.

@ThorpeJosh

2022-10-11 03:03 UTC, merged