sanity check date prior to submission
ThorpeJosh/tp-timesheet pull request #39
Opened 2022-10-12 03:24 UTC by changukshin

- write one function to do sanity check (date_utils.check_date)
- add one option to config (max_submit_within_days)
- logics for version compatibility
    - unfamilliar with this implementation. may need to be modified.

2022-10-12 05:16 UTC, ThorpeJosh requested changes

2022-10-12 05:16 UTC, ThorpeJosh commented on tp_timesheet/date_utils.py
> +    config = Config()
I don't think we should create another config object as `Config.__init__` performs read/writes to disk.
`Config.MAX_DAYS` should return what we are after as it is a class object

2022-10-12 05:16 UTC, ThorpeJosh commented on tp_timesheet/date_utils.py
> +            f"and submitting beyond '{config.MAX_DAYS}' day is not recommended.\n"
```suggestion
            f"The entered date '{start_date_str}' "
            f"is beyond the '{config.MAX_DAYS}' day window from today.\n"
```

2022-10-12 05:16 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +    check_date(start_date)
maybe to make it more obvious what this function does and that it doesn't return anything, we can call it `assert_start_date`

2022-10-12 07:05 UTC, changukshin commented on tp_timesheet/date_utils.py
> +            "You can modify the threshold and/or disable this confirmation option from '{config.CONFIG_PATH}'.\n"
Addressed on f5d3ef4.

2022-10-12 07:05 UTC, changukshin commented on tp_timesheet/date_utils.py
> +            f"and submitting beyond '{config.MAX_DAYS}' day is not recommended.\n"
Addressed on f5d3ef4.

2022-10-12 07:05 UTC, changukshin commented on tp_timesheet/date_utils.py
> +            f"Do you want to submit the timesheet of the date?[y/N]: "
Addressed on f5d3ef4.

2022-10-12 07:05 UTC, changukshin commented on tp_timesheet/__main__.py
> +    check_date(start_date)
Addressed on f5d3ef4.

2022-10-12 07:16 UTC, ThorpeJosh requested changes
Looks good. Just needs to be rebased as `main` has changed causing merge conflicts. (this is why Jenkins cannot run the `pr-merge` check)

2022-10-17 05:42 UTC, ThorpeJosh requested changes
Thanks for the changes @changukshin.

I'm being a bit picky now but would be great to have unit tests written for all new code now that we have a pipeline setup.

2022-10-17 05:42 UTC, ThorpeJosh commented on tp_timesheet/config.py
> +        for config_key in ["check_max_days", "max_submit_within_days"]:
```suggestion
        for config_key in cls.DEFAULT:
```
Shouldn't have these values hard coded twice. Can iterate over the dictionary keys like this.

2022-10-17 05:42 UTC, ThorpeJosh commented on tp_timesheet/date_utils.py
> +def assert_start_date(start_date):
Can you please add a unit test for this function?

2022-10-17 05:45 UTC, ThorpeJosh requested changes
Thanks for the changes @changukshin.

I'm being a bit picky now but would be great to have unit tests written for all new code now that we have a pipeline setup.

2022-10-17 05:45 UTC, ThorpeJosh commented on tp_timesheet/config.py
> +        # Version compatibility (#20)
Can we please write a unit to check the following cases:

case 1:
* Given no `tp.conf` exists
* When a `config.Config()` object is created
* Then `tp.conf` is created and populated with the default values

case 2:
* Given `tp.conf` exists
* When a `config.Config()` object is created
* Then `tp.conf` is updated with missing keys and their default values

2022-10-25 13:53 UTC, changukshin commented on tp_timesheet/date_utils.py
> +def assert_start_date(start_date):
This function have to get users input to confirm.
Do you have any idea to pass imitated confirmation to the function when you test any function which get the keyboard input of user?

2022-10-29 07:56 UTC, changukshin commented on tp_timesheet/date_utils.py
> +def assert_start_date(start_date):
I found a way to manipulate. On progress.

2022-10-29 08:45 UTC, changukshin commented on tp_timesheet/config.py
> +        # Version compatibility (#20)
On it!

2022-11-11 03:20 UTC, ThorpeJosh commented
@changukshin You happy for me to rebase this?

2022-11-11 03:22 UTC, changukshin commented
@ThorpeJosh Sure. Thank you. I have something to do so I have no slot to follow this. Sorry for this delay.

2022-11-11 09:56 UTC, ThorpeJosh commented
> @ThorpeJosh Sure. Thank you. I have something to do so I have no slot to follow this. Sorry for this delay.

No stress. Raised a new PR #57 with this work

2022-11-14 05:42 UTC, closed without merging