feat: pop up dialog if code runs into exception
ThorpeJosh/tp-timesheet pull request #52
Opened 2022-11-04 07:15 UTC by siewyeng

This is a draft for addressing part of issue #49. The code is not concise and these are the things raised by pylint:
`************* Module tp_timesheet.__main__
tp_timesheet/__main__.py:120:0: C0301: Line too long (141/120) (line-too-long)
tp_timesheet/__main__.py:159:0: C0301: Line too long (125/120) (line-too-long)
tp_timesheet/__main__.py:161:0: C0301: Line too long (141/120) (line-too-long)
tp_timesheet/__main__.py:172:0: C0301: Line too long (141/120) (line-too-long)
tp_timesheet/__main__.py:163:11: W0703: Catching too general exception Exception (broad-except)
tp_timesheet/__main__.py:69:0: R0912: Too many branches (21/15) (too-many-branches)
tp_timesheet/__main__.py:69:0: R0915: Too many statements (67/50) (too-many-statements)`

Any suggestions on how to make the exceptions look better? Currently, there is one for when docker fails, one for when selenium fails and one for the general failing. And the `os.system( f"""...` is repeated many times . The message to be logged into the logger is also printed out for now.

2022-11-04 07:43 UTC, siewyeng commented
I changed the code a little do go from catching `Exception as e` to the specific name of the exception because of pylint but this would prevent the code from catching unexpected errors from docker so I am not sure if this is the way to go. @changukshin do you think the pop up should be raised when notifications are turned on (like the successful one) or in all cases (the current code)?

2022-11-07 02:14 UTC, ThorpeJosh requested changes

2022-11-07 02:14 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +            message = re.search(".*\n", str(gen_exception))
Best to send full traceback to the logger to make debugging easier. Can limit the message to the user to a shorter one when needed though.

2022-11-07 02:15 UTC, ThorpeJosh commented
Can also disable the too-many-branches/statements for the run() function.

2022-11-08 07:05 UTC, ThorpeJosh requested changes

2022-11-08 07:05 UTC, ThorpeJosh commented on .pylintrc
> +#                        Exception
Best not to remove this globally but rather just disable it locally within main.py as we don't what this to be used anywhere else except once as a catch-all.

2022-11-08 07:05 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +            "⚠️ TP-timesheet submitted not successfully. Check if Docker is running"
Missed this one @siewyeng

2022-11-14 01:09 UTC, ThorpeJosh requested changes

2022-11-14 01:09 UTC, ThorpeJosh commented on tp_timesheet/submit_form.py
> -        email_field = browser.find_element(
More formatting issues. I think a few of the last commits can be dropped.

2022-11-14 01:09 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +        except Exception as clean_exception:
I think this exception can be more specific. The only two exceptions I can foresee are if docker_handler doesn't exists yet (`NameError`) or if the container was never spun-up (`SomeDockerContainerNotExistsError`).

Otherwise it is probably best to log a warning something like `Ran into unexpected error when attempting to cleanup docker container:....`. This way we can check to see if dangling containers are accumulating.

2022-11-14 01:27 UTC, siewyeng commented on tp_timesheet/__main__.py
> +    # pylint: disable=unused-variable
The `except Exception as clean_exception` on line 180 is causing the unused variable. I think line-too-long is not needed anymore because I changed the pylint. I'll take that away

2022-11-14 01:31 UTC, siewyeng commented on tp_timesheet/__main__.py
> +        except Exception as clean_exception:
Hmmm, okay. I'll do the second option for now!

2022-11-14 01:55 UTC, siewyeng commented on tp_timesheet/__main__.py
> +        except Exception as clean_exception:
would the `SomeDockerContainerNotExistsError` not be covered by line 178?

2022-11-14 02:17 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +    # pylint: disable=unused-variable
Ah right because `clean_exception` is never used. You can just use `except Exception:` without the `as` keyword, in scenarios where you don't want to use the exception message.

2022-11-14 02:19 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +        except Exception as clean_exception:
> would the `SomeDockerContainerNotExistsError` not be covered by line 178?

Correct. It should. I missed that.

So only exception we expect to encounter during the cleanup is if `docker_handler` does not exist (ie. `NameError`)

2022-11-16 08:48 UTC, siewyeng commented
This should address #56 as well

2022-11-16 09:28 UTC, merged