Add get_project_id and get_task_id
ThorpeJosh/tp-timesheet pull request #74
Opened 2022-11-28 08:55 UTC by lamchuntat

2022-11-28 09:41 UTC, lamchuntat commented
Possible area for improvement:

Guard statement in get_project_id() and get_task_id() to check whether workspace id and project_id are already obtained to reduce unnecessary requests.

2022-11-29 02:17 UTC, lamchuntat commented
@ThorpeJosh @siewyeng @changukshin ready for merging

2022-11-29 02:56 UTC, ThorpeJosh requested changes

2022-11-29 02:56 UTC, ThorpeJosh commented on tp_timesheet/clockify_timesheet.py
> +        get_request = requests.get(
The `__init__` method sets the workspace_id now. Infact `workspace_id` never equals `None` it either exists or doesn't so this check won't work.

2022-11-29 02:56 UTC, ThorpeJosh commented on tp_timesheet/clockify_timesheet.py
> +        get_request = requests.get(
Same here. Best to set correct order of operation in the __init__ method instead of performing error handling. This could cause confusing behaviour and make it difficult to debug.

2022-11-29 02:56 UTC, ThorpeJosh commented on tp_timesheet/clockify_timesheet.py
> +            f"https://api.clockify.me/api/v1/workspaces/{self.workspace_id}/projects",
The base URL is defined in class. `self.api_base_endpoint`

2022-11-29 09:31 UTC, merged