Addition of clockify API check
ThorpeJosh/tp-timesheet pull request #75
Opened 2022-11-28 09:48 UTC by siewyeng

warning: the Jenkins environment portion has not been tested

2022-11-29 02:21 UTC, ThorpeJosh requested changes
Looks great. Testing of jenkins environment can be done by checking the Jenkins build logs to see how it is behaving.

2022-11-29 02:21 UTC, ThorpeJosh commented on tp_timesheet/tests/test_config.py
> -def fixture_create_tmp_config():
Can we split this into two fixtures. Maybe `fixture_create_mock_config` and `fixture_create_clockify_api_config`. This way we can get a working config only when needed else we use the mock config.

2022-11-29 02:21 UTC, ThorpeJosh commented on tp_timesheet/tests/test_config.py
> -def fixture_create_tmp_config():
Also change the fixture names to something like `name=mock_config` and `name=clockify_config`

2022-11-29 02:21 UTC, ThorpeJosh commented on tp_timesheet/config.py
> +            while not cls.is_valid_key(clockify_api):
This will break the `test_config_upgrade_process()` test at the following part.

```
# Initialize config which performs the upgrade
with mock.patch.object(builtins, "input", lambda _: new_parameters["clockify_api_key"]):
```

Currently `new_parameters["clockify_api_key"]` returns `change_me` which is invalid and so will get stuck. Can replace it with something like `"A"*50`

2022-12-01 14:30 UTC, ThorpeJosh commented
@siewyeng Can you please move the last commit to a separate PR or one of the other PRs as it isn't relevant to this one.

2022-12-02 01:18 UTC, changukshin commented
@ThorpeJosh [3da12c7](https://github.com/ThorpeJosh/tp-timesheet/pull/75/commits/3da12c725f2da98143e36322c311d88cf38fba7e) was introduced on this branch by incident(my mistake).
I copied that commit on the branch of #59, so please delete that commit on this branch @siewyeng. Sorry for my mistake.

2022-12-02 03:21 UTC, siewyeng commented
@changukshin no worries!

2022-12-02 08:03 UTC, ThorpeJosh requested changes
Looks great.

PR-merge build is failing. Might need rebasing

2022-12-02 08:03 UTC, ThorpeJosh commented on tp_timesheet/tests/test_config.py
> +    print(config_str)
Debug code

2022-12-02 08:11 UTC, siewyeng commented on tp_timesheet/tests/test_config.py
> +    print(config_str)
Okay, I've rebased it. but @ThorpeJosh what do you mean? do you want to add logging here?

2022-12-05 00:57 UTC, ThorpeJosh commented on tp_timesheet/tests/test_config.py
> +    print(config_str)
Sorry, just meant that you can remove the print statement. I presume you put this in here for debugging.
Print statements clutter the stdout for all tests as you can see in Jenkins.

2022-12-05 02:33 UTC, merged