Add locale tags to submission
ThorpeJosh/tp-timesheet pull request #89
Opened 2022-12-05 08:44 UTC by siewyeng

note: 
- the locale_tag is en_SG for the sake of clockify_config test
- only the locales used in this office are supported for now
- unit tests not set up yet locale id

2022-12-05 08:58 UTC, ThorpeJosh approved these changes

2022-12-05 09:01 UTC, ThorpeJosh commented on tp_timesheet/config.py
> +    def is_valid_locale(locale):
can check `locale in list(Clockify.tag_dict.keys())`

2022-12-06 01:26 UTC, ThorpeJosh requested changes

2022-12-06 01:26 UTC, ThorpeJosh commented on tp_timesheet/clockify_timesheet.py
> +    # pylint: disable=too-many-instance-attributes
I think it's ok to bump .pylintrc line447 `max-attributes=7` to `=10`

2022-12-06 01:26 UTC, ThorpeJosh commented on tp_timesheet/config.py
> +            locale_tag = input("Enter locale tag:")
Sorry. I'd put `{poss_locales}` here too rather than wait for user to make a mistake first haha

2022-12-06 01:26 UTC, ThorpeJosh commented on tp_timesheet/config.py
> +    def is_valid_locale(locale):
Reading the code on how the config is loaded, this function is only called if the `tp.conf` did not already contain a `locale_tag` field. If it does, then this function isn't called, so I think it is still okay to check the dict keys.

Does it break somewhere else that I am not seeing?

2022-12-06 01:47 UTC, ThorpeJosh commented on tp_timesheet/clockify_timesheet.py
> +    }
`GET /workspaces/{workspaceId}/tags` returns a list of available tags with their ids and names.
eg) 
```json
[
    {
        "id": "63519fde28051215c2de5647",
        "name": "en_SG",
        "workspaceId": "5fa423e902f38d2ce68f3169",
        "archived": false
    },
    {
        "id": "62d5a8fe3e5f5620105b6227",
        "name": "en_US",
        "workspaceId": "5fa423e902f38d2ce68f3169",
        "archived": false
    }
]
```
It's better to get the ids from clockify than hardcode them. But the list locale names that we support should be hardcoded and then the ids fetched from clockify when class is initiated

2022-12-06 02:00 UTC, siewyeng commented on tp_timesheet/config.py
> +    def is_valid_locale(locale):
Ah it was my mistake. I thought that because DEFAULT_CONF had to be changed and we are checking if the value has not been changed from the default (in `_read_write_config`), the value had to be a non-possible one which made it a little more complicated for `test_config_upgrade_process` as another input would have been needed. I'll change it

2022-12-06 07:09 UTC, ThorpeJosh approved these changes

2022-12-06 07:09 UTC, merged