59 allow training hours to be submitted
ThorpeJosh/tp-timesheet pull request #97
Opened 2022-12-12 09:14 UTC by changukshin

Not ready to merge.
Need below jobs to do.

- [ ] live test for clockify
- [ ] live test for timesheet

I will tag and request review for you when I pass all of above tests.

2022-12-16 01:23 UTC, changukshin commented
All settled. Review required.
@ThorpeJosh @siewyeng @lamchuntat

2022-12-16 01:58 UTC, siewyeng commented on tp_timesheet/tests/test_clockify.py
>      # Add a clockify entry with 1 hour
small comment, could you change this commend of 1 hour too

2022-12-16 03:34 UTC, changukshin commented on tp_timesheet/tests/test_clockify.py
>      # Add a clockify entry with 1 hour
Resolved with 8be4f69. Thanks for your review. @siewyeng

2022-12-16 03:36 UTC, siewyeng approved these changes

2022-12-16 07:59 UTC, ThorpeJosh requested changes
This is fairly large. A lot going on here. Nice work on the new interface!

2022-12-16 07:59 UTC, ThorpeJosh commented on .pylintrc
> +max-line-length=130
I'd try to avoid going over 120.
The python line length standards I've seen are 88, 100 or 120. 120 is the default width of most modern shell windows when you open them.

2022-12-16 07:59 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +        + 'Passing multiple task-hour pair is also acceptable. (ex, "--task live 4 --task OOO 4" for afternoon OOO.)',
```suggestion
        + 'Passing multiple task-hour pair is also acceptable. (E.g. "--task live 4 --task OOO 4" for afternoon OOO.)',
```
`e.g.` means "for example"

2022-12-16 07:59 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +    args.task = {k: int(v) for (k, v) in args.task}
```suggestion
    args.task = {task_name: int(hours) for (task_name, hours) in args.task}
```
Just to be more obvious about what the tuple contents are.

2022-12-16 07:59 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +    logger.debug("Given task and hour pairs : %s", args.task)
I'd log this before calculating the sum and potentially raising the ValueError. Will make it easier to debug.

2022-12-16 07:59 UTC, ThorpeJosh commented on tp_timesheet/__main__.py
> +            "\tHolidays : %s", [f"{date}: 0 hours(holiday)" for date in holidays]
These three logs are going to be slit across multiple lines. Does this look messy?

The first log implies it will have dates but only the 2nd and 3rd supply them. I'd consider rewording the log messages or combine into a single log message.

2022-12-16 07:59 UTC, ThorpeJosh commented on tp_timesheet/clockify_timesheet.py
> +        project_id = self.get_project_id(task)
This adds a lot more api requests. Instead of getting the project_id once when instance is created, we are getting it every time we submit an entry. Is this avoidable? I think the build failures might be due to hitting the api requests rate limit.

2022-12-16 07:59 UTC, ThorpeJosh commented on tp_timesheet/submit_form.py
> +        live_hours.send_keys(tasks.get("live", 0))
What does the second argument do here (the `, 0`)? I thought `tasks.get("live")` or `tasks["live"]` is sufficient.

2022-12-16 07:59 UTC, ThorpeJosh commented on tp_timesheet/tests/test_clockify.py
> +
This test is to ensure clockify clears all previous entries when a new submission is submitted. These lines clear the entries making manually making the test pointless.

I know the mechanism for how tasks are submitted has changed so maybe this test needs to be changed. In this form it is testing nothing.

2022-12-16 08:00 UTC, ThorpeJosh commented
> This is fairly large. A lot going on here. Nice work on the new interface!

Might be a few iterations of reviews due to the complexity making it a bit hard to follow.

2022-12-27 02:28 UTC, siewyeng requested changes

2022-12-27 02:28 UTC, siewyeng commented on tp_timesheet/__main__.py
> +    args.task = [["live", "8"]] if not args.task else args.task  # default value
I think this args.task should be a dictionary instead. Otherwise, it'll cause problems in the `tasks.get` of submit_form.py

2022-12-27 02:34 UTC, siewyeng commented on tp_timesheet/__main__.py
> +    args.task = [["live", "8"]] if not args.task else args.task  # default value
The error was found while trying to submit hours for a holiday without indicating the task or number of hours. e.g., `tp-timesheet -s 26/12/2022 -v`. Perhaps we could find a way to add this into the tests

2022-12-28 03:33 UTC, changukshin commented on tp_timesheet/submit_form.py
> +        live_hours.send_keys(tasks.get("live", 0))
If user give the cli `--task training 8`, the dictionary `tasks` would be `{"training":8}`.
And when you query 'live' on it, results differ depends on the method you use.

```
tasks = {"training": 8}

# key exist
tasks.get("trainig") #8 returned

# key not exist
tasks.get("live", 0) #0 returned as "live" key does not exist on dictionary
tasks.get("live") #None returned as "live" key does not exist on dictionary
tasks["live"] #KeyError raised
```

2022-12-28 05:42 UTC, changukshin commented on tp_timesheet/__main__.py
> +    args.task = [["live", "8"]] if not args.task else args.task  # default value
This line does the job. [link](https://github.com/ThorpeJosh/tp-timesheet/pull/97/files/b3ddf3b01398e48ac2a12479aa40fc90b2f50152#diff-f313fbf2e4c858dbd3b88ac2181f480a65443050ac2b02ab120d057527ecf5dbR84)

--

I can't reproduce the error. Could you pass me the error message?

2022-12-28 05:44 UTC, changukshin commented on tp_timesheet/__main__.py
> +    logger.debug("Given task and hour pairs : %s", args.task)
Resolved with [f65f4c0](https://github.com/ThorpeJosh/tp-timesheet/pull/97/commits/f65f4c019a6b2ff302bf47e5207028be75300f61).

2022-12-28 05:44 UTC, changukshin commented on tp_timesheet/__main__.py
> +            "\tHolidays : %s", [f"{date}: 0 hours(holiday)" for date in holidays]
Resolved with [f65f4c0](https://github.com/ThorpeJosh/tp-timesheet/pull/97/commits/f65f4c019a6b2ff302bf47e5207028be75300f61).

2022-12-28 05:44 UTC, changukshin commented on tp_timesheet/clockify_timesheet.py
> +        project_id = self.get_project_id(task)
Resolved with [f65f4c0](https://github.com/ThorpeJosh/tp-timesheet/pull/97/commits/f65f4c019a6b2ff302bf47e5207028be75300f61).

2022-12-28 05:44 UTC, changukshin commented on tp_timesheet/tests/test_clockify.py
> +
Resolved with [f65f4c0](https://github.com/ThorpeJosh/tp-timesheet/pull/97/commits/f65f4c019a6b2ff302bf47e5207028be75300f61).

2022-12-28 05:52 UTC, siewyeng commented on tp_timesheet/__main__.py
> +    args.task = [["live", "8"]] if not args.task else args.task  # default value
This is the error message. <img width="1300" alt="Screenshot 2022-12-28 at 1 49 16 PM" src="https://user-images.githubusercontent.com/59408288/209764274-adaa38db-ab0b-4e9c-897e-0dbe2f5fdf61.png">

2022-12-28 06:01 UTC, changukshin commented
Check failed for Clockify-side error. Let's wait for it to be fixed.

2022-12-28 06:04 UTC, changukshin commented on tp_timesheet/__main__.py
> +    args.task = [["live", "8"]] if not args.task else args.task  # default value
Would you let me know which commit you are on? @siewyeng

2022-12-28 06:09 UTC, siewyeng commented on tp_timesheet/__main__.py
> +    args.task = [["live", "8"]] if not args.task else args.task  # default value
ohhh a super old one.  b3ddf3b

2022-12-28 07:03 UTC, changukshin commented on tp_timesheet/__main__.py
> +    args.task = [["live", "8"]] if not args.task else args.task  # default value
Fixed on [08dddc2](https://github.com/ThorpeJosh/tp-timesheet/pull/97/commits/08dddc2ab865ac5613e20cd796975b366b71b28d). 
Thanks! @siewyeng @chuntatlam

2022-12-28 07:20 UTC, changukshin commented on .pylintrc
> +max-line-length=130
Resolved with [2294baa](https://github.com/ThorpeJosh/tp-timesheet/pull/97/commits/2294baa9792e9cf62b0724cb8a1f634f2e2d8eac).

2023-01-05 03:17 UTC, ThorpeJosh commented
@changukshin I have rebased and resolved all the merge conflicts around the CLI parser and the project ID tests

2023-01-09 03:41 UTC, changukshin commented
Seems all settled. Review required. @ThorpeJosh @siewyeng

2023-01-09 06:02 UTC, ThorpeJosh requested changes

2023-01-09 08:45 UTC, changukshin commented on tp_timesheet/clockify_timesheet.py
> +        if project in self.project_id_cache:
Resolved with 05d10d

2023-01-09 08:45 UTC, changukshin commented on tp_timesheet/clockify_timesheet.py
> +                self.project_id_cache[project] = dic["id"]
Resolved with 05d10d

2023-01-09 08:46 UTC, changukshin commented on tp_timesheet/clockify_timesheet.py
> +            start_time = datetime.time(start_time.hour + hour, 0)
Resolved with [3809add](https://github.com/ThorpeJosh/tp-timesheet/pull/97/commits/3809addcd3ad7b50820d920378a9ffb838517faa)

2023-01-09 09:22 UTC, ThorpeJosh approved these changes

2023-01-09 09:26 UTC, changukshin commented on tp_timesheet/__main__.py
> +    args.task = [["live", "8"]] if not args.task else args.task  # default value
@siewyeng Could you verify if it is resolved? I think it is okay now!

2023-02-02 05:08 UTC, merged